OBYS.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OBYS.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OBYS.WebUI/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using OBYS.Core.Service;
using OBYS.Model.Entities;
using System.Linq;

namespace OBYS.WebUI.Controllers
{
    public class LessonController : Controller
    {
        private readonly ICoreService<Lesson> _les;

        public LessonController(ICoreService<Lesson> les)
        {
            _les = les;
        }

        // Metodun amacı kayıtları liste olarak göstermek
        public IActionResult Listele()
        {
            return View(_les.GetAll());
        }

        // Metodun amacı yeni kayıt ekleme sayfasını göstermek
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Lesson l)
        {
            if (l.LessonName != null)
            {
                return _les.Add(l) ? View("Listele", _les.GetAll()) : View();
            }

            ViewBag.LessonAddError = "Ders Adını Boş Geçemezsiniz";
            return View();
        }

        public IActionResult Guncelle(int id)
        {
            return View(_les.GetByID(id));
        }

        [HttpPost]
        public IActionResult Guncelle(Lesson l)
        {
            if (l.LessonName != null)
            {
                return _les.Update(l) ? View("Listele", _les.GetAll()) : View();
            }

            ViewBag.LessonUpdateError = "Ders Adını boş bırakamazsınız";
            return View();
        }

        public IActionResult Sil(int id)
        {
            return _les.Delete(id) ? View("Listele", _les.GetAll()) : View();
        }
    }
}

OBYS.WebUI/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using OBYS.Core.Service;
using OBYS.Model.Entities;

namespace OBYS.WebUI.Controllers
{
    public class StudentController : Controller
    {
        private readonly ICoreService<Student> _stu;

        public StudentController(ICoreService<Student> stu)
        {
            _stu= stu;
        }

        public IActionResult Listele()
        {
            return View(_stu.GetAll());
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Student s)
        {
            if (s.StudentName != null && s.StudentSurname != null && s.Gender != null)
            {
                return _stu.Add(s) ? View("Listele", _stu.GetAll()) : View();
            }

            ViewBag.StudentAddError = "İsim, Soyisim ve Cinsiyet boş geçilemez";
            return View();
        }

        public IActionResult Guncelle(int id)
        {
            return View(_stu.GetByID(id));
        }

        [HttpPost]
        public IActionResult Guncelle(Student s)
        {
            if (s.StudentName != null && s.StudentSurname != null && s.Gender != null)
            {
                return _stu.Update(s) ? View("Listele", _stu.GetAll()) : View();
            }

            ViewBag.StudentUpdateError = "İsim, Soyisim ve Cinsiyet boş geçilemez";
            return View();
        }

        public IActionResult Sil(int id)
        {
            return _stu.Delete(id) ? View("Listele", _stu.GetAll()) : View();
        }
    }
}

OBYS.WebUI/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using OBYS.Core.Service;
using OBYS.Model.Entities;

namespace OBYS.WebUI.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ICoreService<Teacher> _t;

        public TeacherController(ICoreService<Teacher> t)
        {
            _t = t;
        }

        public IActionResult Listele()
        {
            return View(_t.GetAll());
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Teacher t)
        {
            if (t.TeacherName != null && t.TeacherSurname != null)
            {
                return _t.Add(t) ? View("Listele", _t.GetAll()) : View();
            }

            return View();
        }
    }
}

OBYS.WebUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OBYS.WebUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OBYS.WebUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OBYS.WebUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OBYS.WebUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OBYS.WebUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OBYS.WebUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OBYS.WebUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OBYS.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OBYS.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OBYS.WebUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OBYS.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ANASAYFA</h1>

OBYS.WebUI/Views/Lesson/Ekle.cshtml
@model Lesson
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yeni Ders Ekle</h1>

@if (ViewBag.LessonAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.LessonAddError
    </div>
}

<form asp-controller="Lesson" asp-action="Ekle" method="post">
    <input type="text" name="LessonName" placeholder="Ders Adı Giriniz" /><br /><br />
    <input type="submit" value="Kaydet" class="btn btn-success" />
</form>

OBYS.WebUI/Views/Lesson/Guncelle.cshtml
@model Lesson
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Kayıt Güncelle</h1>

@if (ViewBag.LessonUpdateError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.LessonUpdateError
    </div>
}
else
{
   <form asp-controller="Lesson" asp-action="Guncelle" method="post">
        <input type="hidden" name="ID" value="@Model.ID" />
        <input type="text" name="LessonName" value="@Model.LessonName" placeholder="Ders Adı Giriniz" /><br /><br />
        <input type="submit" value="Güncelle" class="btn btn-success" />
   </form> 
}

OBYS.WebUI/Views/Lesson/Listele.cshtml
@model IEnumerable<Lesson>
@{
    ViewData["Title"] = "Listele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Ders Listelesi</h1>

@if (Model.Count() == 0)
{
    <div class="alert alert-danger" role="alert">
      Kayıt Bulunamadı..!
    </div>
}
else
{
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Ders Adı</th>
          <th scope="col">###</th>
          <th scope="col">###</th>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model)
        {
           <tr>
              <th scope="row">@item.ID</th>
              <td>@item.LessonName</td>
              <td><a asp-controller="Lesson" asp-action="Guncelle" asp-route-id="@item.ID" class="btn btn-success">Güncelle</a></td>
              <td><a asp-controller="Lesson" asp-action="Sil" asp-route-id="@item.ID" class="btn btn-danger">Sil</a></td>
           </tr>      
        }
      </tbody>
    </table>    
}

OBYS.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OBYS.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OBYS.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Listele">Öğrenci Listesi</a>
                            <a class="nav-link text-dark" asp-controller="Lesson" asp-action="Listele">Ders Listesi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OBYS.WebUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OBYS.WebUI/Views/Student/Ekle.cshtml
@model Student
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yeni Öğrenci Ekle</h1>

@if (ViewBag.StudentAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.StudentAddError
    </div>
}

<form asp-controller="Student" asp-action="Ekle" method="post">
    <input type="text" name="StudentName" placeholder="Öğrenci Adı Giriniz" /><br /><br />
    <input type="text" name="StudentSurname" placeholder="Öğrenci Soyadı Giriniz" /><br /><br />
    <select class="custom-select" name="Gender">
        <option selected>Cinsiyet Seçiniz</option>
        <option value="Erkek">Erkek</option>
        <option value="Bayan">Bayan</option>
    </select>
    <input type="submit" value="Kaydet" class="btn btn-success" />
</form>

OBYS.WebUI/Views/Student/Guncelle.cshtml
@model Student
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Kayıt Güncelle</h1>

@if (ViewBag.StudentUpdateError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.StudentUpdateError
    </div>
}
else
{
    <form asp-controller="Student" asp-action="Guncelle" method="post">
        <input type="hidden" name="ID" value="@Model.ID" />
        <input type="text" name="StudentName" value="@Model.StudentName" placeholder="Öğrenci Adı Giriniz" /><br />
        <input type="text" name="StudentSurname" value="@Model.StudentSurname" placeholder="Öğrenci Soyadı Giriniz" /><br />
        <input type="text" name="Gender" value="@Model.Gender" placeholder="Cinsiyet Giriniz" /><br />
        <input type="submit" value="Güncelle" class="btn btn-success" />
    </form>
}

OBYS.WebUI/Views/Student/Listele.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Listele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Öğrenci Listelesi</h1>

@if (Model.Count() == 0)
{
    <div class="alert alert-danger" role="alert">
        Kayıt Bulunamadı..!
    </div>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Öğrenci Adı</th>
                <th scope="col">###</th>
                <th scope="col">###</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.StudentName &nbsp; @item.StudentSurname</td>
                    <td><a asp-controller="Student" asp-action="Guncelle" asp-route-id="@item.ID" class="btn btn-success">Güncelle</a></td>
                    <td><a asp-controller="Student" asp-action="Sil" asp-route-id="@item.ID" class="btn btn-danger">Sil</a></td>
                </tr>
            }
        </tbody>
    </table>
}

OBYS.WebUI/Views/Teacher/Ekle.cshtml
@model Teacher
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Yeni Öğretmen Ekle</h1>

@if (ViewBag.TeacherAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.TeacherAddError
    </div>
}

<form asp-controller="Teacher" asp-action="Ekle" method="post">
    <input type="text" name="TeacherName" placeholder="Öğretmen Adı Giriniz" /><br /><br />
    <input type="text" name="TeacherSurname" placeholder="Öğretmen Soyadı Giriniz" /><br /><br />
    <select class="custom-select" name="LessonID">
        <option selected>Ders Seçiniz</option>
        <option value="1">Matematik</option>
        <option value="2">Türkçe</option>
    </select>
    <input type="submit" value="Kaydet" class="btn btn-success" />
</form>